name: isyarat_kita

description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.0.2
  firebase_core: ^3.10.1
  cloudinary_flutter: ^1.0.0
  cloudinary_url_gen: ^1.0.0
  http: ^1.3.0
  image_picker: ^1.1.2
  cloud_firestore: ^5.6.2
  uuid: ^4.5.1
  firebase_auth: ^5.4.1
  awesome_snackbar_content: ^0.1.5
  camera: ^0.11.0+2
  permission_handler: ^11.3.1
  path_provider: ^2.1.5
  google_ml_kit: ^0.19.0
  localstorage: ^4.0.0
  flutter_secure_storage: ^9.2.4
  gal: ^2.3.1
  tflite_flutter: ^0.11.0 #untuk sambungin ke model ml

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/images/
    - assets/icons/